import type { JSONSchema7 } from "json-schema";
import type { DeepPartial, TypeAtPath, TypePath } from "./type-path-utils";
import type { AsyncIterableStream } from "../../utils";
import type { StandardSchemaV1 } from "@standard-schema/spec";
import type { ToolResponse } from "./ToolResponse";

export type ToolModelContentPart =
  | {
      /** A text content part returned to the model after a tool call. */
      readonly type: "text";
      /** Text that should be included in the model-visible tool result. */
      readonly text: string;
    }
  | {
      /** A file content part returned to the model after a tool call. */
      readonly type: "file";
      /**
       * File payload encoded as a provider-compatible string, commonly base64
       * for binary data.
       */
      readonly data: string;
      /** MIME type for the file payload. */
      readonly mediaType: string;
      /** Optional display filename for the file payload. */
      readonly filename?: string;
    };

/**
 * Converts a tool's runtime result into content that is sent back to the
 * model.
 *
 * Return this when the value shown in the UI or stored as the tool result
 * should differ from the model-visible response. When omitted, the successful
 * tool result is sent back to the model as-is. If a tool returns a
 * `ToolResponse` with `modelContent`, that explicit content is used instead
 * of calling this function.
 *
 * @example
 * ```ts
 * const toModelOutput: ToolModelOutputFunction<
 *   { documentId: string },
 *   { summary: string; pdfBase64: string }
 * > = ({ output }) => [
 *   { type: "text", text: output.summary },
 *   {
 *     type: "file",
 *     data: output.pdfBase64,
 *     mediaType: "application/pdf",
 *   },
 * ];
 * ```
 */
export type ToolModelOutputFunction<TArgs, TResult> = (options: {
  /** Stable identifier for the tool call being converted. */
  toolCallId: string;
  /** Arguments supplied by the model for this tool call. */
  input: TArgs;
  /** Value returned by the tool's {@link ToolExecuteFunction}. */
  output: TResult;
}) =>
  | readonly ToolModelContentPart[]
  | Promise<readonly ToolModelContentPart[]>;

/**
 * Interface for reading tool call arguments from a stream, which are
 * generated by a language learning model (LLM). Provides methods to
 * retrieve specific values, partial streams, or complete items from
 * an array, based on a specified path.
 *
 * @template TArgs The type of arguments being read.
 */
export interface ToolCallArgsReader<TArgs extends Record<string, unknown>> {
  /**
   * Returns a promise that will resolve to the value at the given path,
   * as soon as that path is generated by the LLM.
   *
   * @param fieldPath An array of object keys or array indices.
   */
  get<PathT extends TypePath<TArgs>>(
    ...fieldPath: PathT
  ): Promise<TypeAtPath<TArgs, PathT>>;

  /**
   * Returns a stream that will emit partial values at the given path,
   * as they are generated by the LLM.
   *
   * @param fieldPath An array of object keys or array indices.
   */
  streamValues<PathT extends TypePath<TArgs>>(
    ...fieldPath: PathT
  ): AsyncIterableStream<DeepPartial<TypeAtPath<TArgs, PathT>>>;

  /**
   * Returns a stream that will emit partial text at the given path,
   * as they are generated by the LLM.
   *
   * @param fieldPath An array of object keys or array indices.
   */
  streamText<PathT extends TypePath<TArgs>>(
    ...fieldPath: PathT
  ): TypeAtPath<TArgs, PathT> extends string & infer U
    ? AsyncIterableStream<U>
    : never;

  /**
   * Returns a stream that will emit complete items in the array
   * at the given path, as they are generated by the LLM.
   *
   * @param fieldPath An array of object keys or array indices.
   */
  forEach<PathT extends TypePath<TArgs>>(
    ...fieldPath: PathT
  ): TypeAtPath<TArgs, PathT> extends Array<infer U>
    ? AsyncIterableStream<U>
    : never;
}

export interface ToolCallResponseReader<TResult> {
  get: () => Promise<ToolResponse<TResult>>;
}

export interface ToolCallReader<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> {
  args: ToolCallArgsReader<TArgs>;
  response: ToolCallResponseReader<TResult>;

  /**
   * @deprecated Use {@link ToolCallReader.response} and read
   * `response.get().result` instead.
   */
  result: {
    get: () => Promise<TResult>;
  };
}

export type ToolExecutionContext = {
  /** Stable identifier for the tool call being executed. */
  toolCallId: string;
  /** Signal that is aborted when the current run is cancelled. */
  abortSignal: AbortSignal;
  /**
   * From inside a frontend tool's execute function, request human input from
   * the UI. Resolves with the payload the UI supplies.
   */
  human: (payload: unknown) => Promise<unknown>;
};

/**
 * Function called when assistant-ui executes a frontend tool.
 */
export type ToolExecuteFunction<TArgs, TResult> = (
  args: TArgs,
  context: ToolExecutionContext,
) => TResult | Promise<TResult>;

export type ToolStreamCallFunction<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> = (
  reader: ToolCallReader<TArgs, TResult>,
  context: ToolExecutionContext,
) => void;

type OnSchemaValidationErrorFunction<TResult> = ToolExecuteFunction<
  unknown,
  TResult
>;

type ToolBase<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> = {
  /**
   * @deprecated Experimental, API may change.
   */
  streamCall?: ToolStreamCallFunction<TArgs, TResult>;
};

type BackendTool<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> = ToolBase<TArgs, TResult> & {
  /** Tool that is executed by the backend rather than in the browser. */
  type: "backend";

  description?: undefined;
  parameters?: undefined;
  disabled?: undefined;
  execute?: undefined;
  toModelOutput?: undefined;
  experimental_onSchemaValidationError?: undefined;
};

type FrontendTool<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> = ToolBase<TArgs, TResult> & {
  /** Tool that is executed in the frontend runtime. */
  type: "frontend";

  /** Natural-language description shown to the model when selecting tools. */
  description?: string | undefined;
  /** Schema for the arguments the model must provide when calling the tool. */
  parameters: StandardSchemaV1<TArgs> | JSONSchema7;
  /** Prevents the tool from being exposed to the model while true. */
  disabled?: boolean;
  /** Executes the tool after the model provides valid arguments. */
  execute: ToolExecuteFunction<TArgs, TResult>;
  /** Converts the execution result into model-visible output. */
  toModelOutput?: ToolModelOutputFunction<TArgs, TResult>;
  /** Handles invalid tool arguments when schema validation fails. */
  experimental_onSchemaValidationError?: OnSchemaValidationErrorFunction<TResult>;
};

type HumanTool<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> = ToolBase<TArgs, TResult> & {
  /** Tool that pauses the run until a user or UI supplies a result. */
  type: "human";

  /** Natural-language description shown to the model when selecting tools. */
  description?: string | undefined;
  /** Schema for the arguments the model must provide when requesting input. */
  parameters: StandardSchemaV1<TArgs> | JSONSchema7;
  /** Prevents the tool from being exposed to the model while true. */
  disabled?: boolean;
  execute?: undefined;
  toModelOutput?: undefined;
  experimental_onSchemaValidationError?: undefined;
};

/**
 * Definition for a tool that can be exposed to the assistant model.
 *
 * Use `type: "frontend"` for tools executed in the browser, `type: "backend"`
 * for tools handled by your server, and `type: "human"` for flows that pause
 * until the UI supplies a result.
 *
 * @example
 * ```ts
 * const frontendTool: Tool<{ city: string }, string> = {
 *   type: "frontend",
 *   description: "Get the weather for a city.",
 *   parameters: {
 *     type: "object",
 *     properties: { city: { type: "string" } },
 *     required: ["city"],
 *   },
 *   execute: async ({ city }) => `Sunny in ${city}`,
 * };
 * ```
 *
 * @example
 * ```ts
 * const backendTool: Tool = {
 *   type: "backend",
 * };
 * ```
 *
 * @example
 * ```ts
 * const humanTool: Tool<{ question: string }, string> = {
 *   type: "human",
 *   description: "Ask the user a follow-up question.",
 *   parameters: {
 *     type: "object",
 *     properties: { question: { type: "string" } },
 *     required: ["question"],
 *   },
 * };
 * ```
 */
export type Tool<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> =
  | FrontendTool<TArgs, TResult>
  | BackendTool<TArgs, TResult>
  | HumanTool<TArgs, TResult>
  | ToolWithoutType<TArgs, TResult>;

/**
 * @deprecated Use {@link Tool} with an explicit `type` field instead.
 */
export type ToolWithoutType<
  TArgs extends Record<string, unknown> = Record<string, unknown>,
  TResult = unknown,
> = (
  | Omit<FrontendTool<TArgs, TResult>, "type">
  | Omit<BackendTool<TArgs, TResult>, "type">
  | Omit<HumanTool<TArgs, TResult>, "type">
) & { type?: undefined };
