import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import { buildCatalog, type CatalogPage } from "../lib/catalog/build";
import { catalogItemSchema } from "../lib/catalog/schema";

const docsRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = resolve(docsRoot, "content/examples");
const outputPath = resolve(docsRoot, ".source/catalog.ts");

async function findMdxFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((entry) => {
      const path = resolve(directory, entry.name);
      return entry.isDirectory()
        ? findMdxFiles(path)
        : Promise.resolve(entry.name.endsWith(".mdx") ? [path] : []);
    }),
  );
  return nested.flat();
}

function pageUrl(filePath: string) {
  const path = relative(contentRoot, filePath)
    .split(sep)
    .join("/")
    .replace(/\.mdx$/, "")
    .replace(/(^|\/)index$/, "");
  return `/examples${path ? `/${path}` : ""}`;
}

function readFrontmatter(source: string, filePath: string) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(source);
  if (!match) throw new Error(`${filePath} has no YAML frontmatter`);
  return parse(match[1]!) as Record<string, unknown>;
}

const files = await findMdxFiles(contentRoot);
const pages: CatalogPage[] = await Promise.all(
  files.map(async (filePath) => {
    const data = readFrontmatter(await readFile(filePath, "utf8"), filePath);
    const catalog = data.catalog
      ? catalogItemSchema.parse(data.catalog)
      : undefined;
    return {
      url: pageUrl(filePath),
      data: {
        title: typeof data.title === "string" ? data.title : undefined,
        description:
          typeof data.description === "string" ? data.description : undefined,
        catalog,
      },
    };
  }),
);

const catalog = buildCatalog(pages);
const generated = `// Generated by scripts/generate-catalog.mts. Do not edit.\nimport type { Catalog } from \"@/lib/catalog/build\";\n\nexport const catalog: Catalog = ${JSON.stringify(catalog, null, 2)};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated);
console.log(`Generated ${catalog.items.length} catalog items`);
